name: CI Android

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y p7zip-full curl

    - name: Download RetroArch assets
      run: |
        curl -L https://github.com/libretro/retroarch-assets/releases/download/Latest/assets.7z -o assets.7z
        7z x assets.7z -oassets

    - name: Compile RA
      run: |
        cd pkg/android/phoenix
        # Copiar assets para o build
        cp -r ../../assets/* assets/
        ./gradlew assembleDebug
        find . -iname "*.apk" -exec ls -l "{}" \;

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - uses: actions/upload-artifact@v4
      with:
        name: retroarch-android-${{ steps.slug.outputs.sha8 }}
        path: |
          pkg/android/phoenix/build/outputs/apk/normal/debug/phoenix-normal-debug.apk
