name: CI Android - Phoenix & Phoenix64

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-phoenix:
    runs-on: ubuntu-22.04
    name: Build Phoenix (debug-tvbox)
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip

      - name: Compile Phoenix - debug-tvbox
        run: |
          cd pkg/android/phoenix
          # Os assets já estão presentes no repositório
          ./gradlew assembleDebug
          find . -iname "*.apk" -exec ls -l "{}" \;

      - name: Get short SHA
        id: slug_phoenix
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - uses: actions/upload-artifact@v4
        with:
          name: retroarch-phoenix-${{ steps.slug_phoenix.outputs.sha8 }}
          path: |
            pkg/android/phoenix/build/outputs/apk/tvbox/debug/phoenix-tvbox-debug.apk

  build-phoenix64:
    runs-on: ubuntu-22.04
    name: Build Phoenix64 (debug-celular)
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip

      - name: Compile Phoenix64 - debug-celular
        run: |
          cd pkg/android/phoenix64
          # Os assets já estão presentes no repositório
          ./gradlew assembleDebug
          find . -iname "*.apk" -exec ls -l "{}" \;

      - name: Get short SHA
        id: slug_phoenix64
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - uses: actions/upload-artifact@v4
        with:
          name: retroarch-phoenix64-${{ steps.slug_phoenix64.outputs.sha8 }}
          path: |
            pkg/android/phoenix64/build/outputs/apk/celular/debug/phoenix-celular-debug.apk
