name: (Debug) CI Android - Phoenix & Phoenix64

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-phoenix:
    runs-on: ubuntu-22.04
    name: Build Phoenix
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip curl

      - name: Set execute permissions recursively
        run: |
          chmod -R 775 pkg/android/phoenix

      - name: Download and update cores (32-bit)
        run: |
          source ./cores.sh
          baixar_cores "armeabi-v7a" "pkg/android/phoenix/assets/cores32" "tmp_cores32"

      - name: Download and update cores (64-bit)
        run: |
          source ./cores.sh
          baixar_cores "arm64-v8a" "pkg/android/phoenix/assets/cores64" "tmp_cores64"

      - name: Compile Phoenix - debug
        run: |
          cd pkg/android/phoenix
          ./gradlew assembleDebug
          find . -iname "*.apk" -exec ls -l "{}" \;

      - name: Get short SHA
        id: slug_phoenix
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Find APK
        run:  |
          find pkg/android/phoenix/build -type f -name "*.apk"

      - uses: actions/upload-artifact@v4
        with:
          name: retroarch-phoenix-debug-${{ steps.slug_phoenix.outputs.sha8 }}
          path: pkg/android/phoenix/build/outputs/apk/normal/debug/phoenix-normal-debug.apk
