name: Generate Android Keystore

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate release keystore
        run: |
          keytool -genkey -v \
            -keystore my-release-key.keystore \
            -alias phoenixkey \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass 123456 \
            -keypass 123456 \
            -dname "CN=Phoenix,O=RetroArch,C=BR"

      - name: Convert keystore to Base64
        run: |
          base64 my-release-key.keystore > my-release-key.keystore.b64

      - name: Upload keystore artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-release-keystore
          path: |
            my-release-key.keystore
            my-release-key.keystore.b64
