name: (Lint) CI Android - Phoenix & Phoenix64

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-phoenix:
    runs-on: ubuntu-22.04
    name: Lint Phoenix (armeabi-v7a)
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip curl openjdk-11-jdk

      - name: Set execute permissions recursively
        run: |
          chmod -R 775 pkg/android/phoenix
          chmod -R 775 pkg/android/phoenix64

      - name: Download and update cores (32-bit)
        run: |
          source ./cores.sh
          baixar_cores "armeabi-v7a" "pkg/android/phoenix/assets/cores" "tmp_cores32"

      - name: Run Lint
        run: |
          cd pkg/android/phoenix
          ./gradlew lintNormalRelease || true

      - name: Find HTML
        run:  |
          find pkg/android/phoenix/build/reports/lint -type f -name "*.html"

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: phoenix-lint-report
          path: pkg/android/phoenix/build/reports/lint/*.html

  lint-phoenix64:
    runs-on: ubuntu-22.04
    name: Lint Phoenix64 (arm64-v8a)
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip curl openjdk-11-jdk

      - name: Set execute permissions recursively
        run: |
          chmod -R 775 pkg/android/phoenix
          chmod -R 775 pkg/android/phoenix64

      - name: Download and update cores (64-bit)
        run: |
          source ./cores.sh
          baixar_cores "arm64-v8a" "pkg/android/phoenix64/assets/cores" "tmp_cores32"

      - name: Run Lint
        run: |
          cd pkg/android/phoenix64
          ./gradlew lintNormalRelease || true

      - name: Find HTML
        run:  |
          find pkg/android/phoenix/build/reports/lint -type f -name "*.html"

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: phoenix64-lint-report
          path: pkg/android/phoenix64/build/reports/lint/*.html
