name: (Test Debug) CI Android - Phoenix & Phoenix64

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-phoenix:
    runs-on: ubuntu-22.04
    name: Build Phoenix
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip curl openjdk-17-jdk
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
          sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

      - name: Set JAVA_HOME and PATH
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH" >> $GITHUB_ENV

      - name: Set execute permissions recursively
        run: |
          chmod -R 775 pkg/android/phoenix

      - name: Download and update cores (32-bit)
        run: |
          source ./cores.sh
          baixar_cores "armeabi-v7a" "pkg/android/phoenix/assets/cores32" "tmp_cores32"

      - name: Download and update cores (64-bit)
        run: |
          source ./cores.sh
          baixar_cores "arm64-v8a" "pkg/android/phoenix/assets/cores64" "tmp_cores64"

      - name: Compile Phoenix - debug
        run: |
          cd pkg/android/phoenix
          ./gradlew assembleDebug
          find . -iname "*.apk" -exec ls -l "{}" \;

      - name: Get short SHA
        id: slug_phoenix
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Find APK
        run:  |
          find pkg/android/phoenix/build -type f -name "*.apk"

      - uses: actions/upload-artifact@v4
        with:
          name: retroarch-phoenix-debug-${{ steps.slug_phoenix.outputs.sha8 }}
          path: pkg/android/phoenix/build/outputs/apk/normal/debug/phoenix-normal-debug.apk 
